### ISSUE TITLE
Trigger compiling when tailwind.config.js changes

### ISSUE THREAD

**Issue by deanfields** [mizziness/craft3-webpack5-tailwind2-boilerplate#3]
Is there a way to trigger a recompile when the tailwind.config.js changes? It's super quick as it is, which is great but it would be nice if it could re-trigger maybe with a command?

**Comment by mizziness** [comment]
@deanfields  Indeed!  You can use the [webpack watch files plugin](https://github.com/Fridus/webpack-watch-files-plugin) like so:

```js
// webpack.dev.js
const WatchExternalFilesPlugin = require('webpack-watch-files-plugin').default;

plugins: [
...
    new WatchExternalFilesPlugin({
      files: [ '../tailwind.config.js' ]
    }),
...
```
