### ISSUE TITLE
Cannot get /

### ISSUE THREAD

**Issue by a-rbsn** [mizziness/craft3-webpack5-tailwind2-boilerplate#4]
I'm not sure why but I'm encountering the following issues:

- `yarn build` seems to successfully apply the css/js in the src folder and create `web/dist/js` and `web/dist/css` accordingly
- `yarn dev` gives the following:
```
(node:55848) [DEP_WEBPACK_WATCH_WITHOUT_CALLBACK] DeprecationWarning: A 'callback' argumen
t need to be provided to the 'webpack(options, callback)' function when the 'watch' option is set. There is no way to handle the 'watch' option without a callback.
(Use `node --trace-deprecation ...` to show where the warning was created)
ℹ ｢wds｣: Project is running at http://localhost:8080/ℹ ｢wds｣: webpack output is served from /
ℹ ｢wds｣: Content not from webpack is served from /Users/andrew/Sites/ahra/src, /Users/andr
ew/Sites/ahra/web/dist, /Users/andrew/Sites/ahra/templates
ℹ ｢wds｣: 404s will fallback to /index.html
ℹ ｢wdm｣: asset chunk-vendors.bundle.js 916 KiB [emitted] (name: chunk-vendors) (id hint: vendors)
asset app.bundle.js 148 KiB [emitted] (name: app)
asset manifest.json 82 bytes [emitted]
Entrypoint app 1.04 MiB = chunk-vendors.bundle.js 916 KiB app.bundle.js 148 KiB
runtime modules 27.2 KiB 13 modules
modules by path ./node_modules/ 348 KiB
  modules by path ./node_modules/webpack-dev-server/ 21.2 KiB 12 modules
  modules by path ./node_modules/webpack/hot/ 4.46 KiB 5 modules
  modules by path ./node_modules/html-entities/lib/*.js 61 KiB 5 modules
  modules by path ./node_modules/querystring/*.js 4.51 KiB 3 modules
  modules by path ./node_modules/url/*.js 23.1 KiB 2 modules
  modules by path ./node_modules/css-loader/dist/runtime/*.js 3.78 KiB
    ./node_modules/css-loader/dist/runtime/cssWithMappingToString.js 2.21 KiB [built] [code generated]
    ./node_modules/css-loader/dist/runtime/api.js 1.57 KiB [built] [code generated]
modules by path ./src/ 17.1 KiB
  ./src/app.js 64 bytes [built] [code generated]
  ./src/app.scss 1.64 KiB [built] [code generated]
  ./node_modules/css-loader/dist/cjs.js??ruleSet[1].rules[1].use[1]!./node_modules/postcss-loader/dist/cjs.js??ruleSet[1].rules[1].use[2]!./node_modules/sass-loader/dist/cjs.js??ruleSet[1].rules[1].use[3]!./src/app.scss 15.4 KiB [built] [code generated]
webpack 5.13.0 compiled successfully in 3793 ms
ℹ ｢wdm｣: Compiled successfully.
```

When I go to `localhost:8080` I get the following error: `Cannot GET /` — when I visit the site locally using Valet at `domain.test` I see the website but none of the CSS is applied. Although this is in DevTools:

```
<script type="module" src="http://localhost:8080/app.bundle.js"></script>
<script type="module" src="http://localhost:8080/app.bundle.js" nomodule=""></script>
<script type="module" src="http://localhost:8080/chunk-vendors.bundle.js"></script>
<script src="http://localhost:8080/chunk-vendors.bundle.js" nomodule=""></script>
```

Any thoughts would be greatly appreciated.

Best,
Andrew

**Comment by claysondesign** [comment]
Getting the same error with a Nitro setup. Can't work out what might have changed. Build is fine.

(node:2896) [DEP_WEBPACK_WATCH_WITHOUT_CALLBACK] DeprecationWarning: A 'callback' argument need to be provided to the 'webpack(options, callback)' function when the 'watch' option is set. There is no way to handle the 'watch' option without a callback.

Have searched on “DEP_WEBPACK_WATCH_WITHOUT_CALLBACK” and seems to be a common problem with many potential solutions.

The webpack hot load seems flakier than Browsersync in this setup? I don’t know. Everything else here works a treat :)

**Comment by Bcdo** [comment]
@claysondesign What is your approach on using this with nitro? I am new with webpack, and I want to test it with nitro, but I get the same issue as described above, and no css or tailwind working.

**Comment by claysondesign** [comment]
More or less using as this repo and have tried a few amends, but it always falls over worse. All paths and assets set up .env or config/general.php seem to working well when not in dev mode.

Nitro works pretty well, but a little limited (no https). Reliant on Multipass on the Mac and apparently not M1 ready either if you’re lucky enough to go there.

If this nice little stack works on Mamp Pro or Valet that would be interesting.

**Comment by claysondesign** [comment]
Have tried this now on a fresh install and Nitro 2.03 BETA

Still the same issue but webpack update and search suggests that in package.json scripts to remove the --watch to prevent further errors

Change:

`    "dev": "cross-env NODE_ENV=development webpack serve --watch --config ./wpconfig/webpack.dev.js",`

to

`    "dev": "cross-env NODE_ENV=development webpack serve --watch --config ./wpconfig/webpack.dev.js",
`

**Comment by mizziness** [comment]
> Have tried this now on a fresh install and Nitro 2.03 BETA
> 
> Still the same issue but webpack update and search suggests that in package.json scripts to remove the --watch to prevent further errors
> 
> Change:
> 
> ` "dev": "cross-env NODE_ENV=development webpack serve --watch --config ./wpconfig/webpack.dev.js",`
> 
> to
> 
> ` "dev": "cross-env NODE_ENV=development webpack serve --config ./wpconfig/webpack.dev.js",`

This appears to be correct - webpack-cli 4.4.0 -> 4.5.0 is where the change occurred.  Update to the project coming :) Thanks!

**Comment by claysondesign** [comment]
Looks good. Does this solve the original "Cannot GET /" issue for you?

Still the same for me on Nitro 2.05 BETA

https://testdomain.nitro/ is fine but Webpack watch url doesn't want to know :( https://testdomain.nitro:8080/

**Comment by williamExitable** [comment]
I have the same problem. When I run` yarn dev ` and I browse to localhost:8080 I get the same message: Cannot get /
The Master repo is today installed. In the package.json I have: `cross-env NODE_ENV=development webpack serve --mode development --config ./wpconfig/webpack.dev.js`

**Comment by BramBeekman** [comment]
> I have the same problem. When I run`yarn dev` and I browse to localhost:8080 I get the same message: Cannot get /
> The Master repo is today installed. In the package.json I have: `cross-env NODE_ENV=development webpack serve --mode development --config ./wpconfig/webpack.dev.js`

The same here, any fix?

**Comment by mizziness** [comment]
@BramBeekman  That is because there's no index file in your `dist` folder - it's not required, though!  The asset files are still served.  If you try and load one directly, it should work. The latest release includes code and instructions on how to make it generate an index file, if you really want one.

**Comment by storybynumbers** [comment]
How are you accessing your homepage when the index file is not being generated? How do you access other templates when no files are generated in web/dist in dev mode?

**Comment by JonQuayle** [comment]
Just chipping in here as I'm also seeing the 'Cannot GET /' message. No errors in the terminal. CSS and JS is being built fine with the build command. I am however using MAMP and I'm not sure how to connect the two? Pretty confused if I'm being honest with how the template files in /templates are getting rendered with Webpack-dev-server?
