### ISSUE TITLE
Yarn dev - Not building css file

### ISSUE THREAD

**Issue by brianbier** [mizziness/craft3-webpack5-tailwind2-boilerplate#6]
Hi I was trying to test out tailwind css but the javascript file is not buildings a css file. When I enter yarn dev, it only builds the app.js and the chunk-vendors.js file.

yarn  build - actually creates a css file but it strips out all the tailwind css.

Do you have any suggestions on how to fix this problem?

**Comment by brianbier** [comment]
<img width="295" alt="Screen Shot 2021-05-29 at 10 01 24 PM" src="https://user-images.githubusercontent.com/11370144/120089537-76dbae00-c0c9-11eb-8479-69fb20b4d999.png">

**Comment by mizziness** [comment]
@brianbier The default `tailwind.config.js` file includes purging unused styles by default - if you disable that feature and build again, you'll see output :)
