### ISSUE TITLE
webpack not generating css/js folders in dist

### ISSUE THREAD

**Issue by Kaustix** [mizziness/craft3-webpack5-tailwind2-boilerplate#8]
Running `yarn dev` only emits the files manifest.json and stats.json, and not creating js/css folders nor any any assets. 

// manifest.json
{
  "app.js": "/js/app.js",
  "chunk-vendors.js": "/js/chunk-vendors.js",
  "app.js.map": "/js/app.js.map",
  "chunk-vendors.js.map": "/js/chunk-vendors.js.map"
}

my current environment is running in WSL2 ubuntu.

yarn run output:

yarn run v1.22.11
$ yarn run clean:dist && cross-env NODE_ENV=development --max_old_space_size=8096 webpack serve --mode development --config ./wpconfig/webpack.dev.js
$ rm -rf ./web/dist/*
<i> [webpack-dev-server] SSL certificate: /home/kaustix/horizon/node_modules/.cache/webpack-dev-server/server.pem
<w> [webpack-dev-server] "hot: true" automatically applies HMR plugin, you don't have to add it manually to your webpack configuration.
    [webpack-cli] Compiler starting... 
    [webpack-cli] Compiler is using config: '/home/kaustix/horizon/wpconfig/webpack.dev.js'
<i> [webpack-dev-server] Project is running at:
<i> [webpack-dev-server] Loopback: https://localhost:8080/, https://127.0.0.1:8080/
<i> [webpack-dev-server] Content not from webpack is served from '/home/kaustix/horizon/templates, /home/kaustix/horizon/src' directory

warn - You have enabled the JIT engine which is currently in preview.
warn - Preview features are not covered by semver, may introduce breaking changes, and can change at any time.
Webpack Bundle Analyzer saved stats file to /home/kaustix/horizon/web/dist/stats.json
    [webpack-cli] Compiler finished
    [webpack-cli] Compiler is watching files for updates...
    [webpack-dev-middleware] Compilation finished
asset js/chunk-vendors.js 923 KiB [emitted] (name: chunk-vendors) (id hint: vendors) 1 related asset
asset js/app.js 87.8 KiB [emitted] (name: app) 1 related asset
asset manifest.json 162 bytes [emitted]
Entrypoint app 1010 KiB (964 KiB) = js/chunk-vendors.js 923 KiB js/app.js 87.8 KiB 2 auxiliary assets
runtime modules 28.3 KiB 14 modules
modules by path ./node_modules/core-js/ 417 KiB 414 modules
modules by path ./node_modules/webpack-dev-server/client/ 50.8 KiB 12 modules
modules by path ./node_modules/webpack/hot/*.js 5.23 KiB 4 modules
modules by path ./node_modules/html-entities/lib/*.js 81.3 KiB 4 modules
modules by path ./src/ 36.9 KiB 3 modules
modules by path ./node_modules/querystring/*.js 4.51 KiB 3 modules
modules by path ./node_modules/url/*.js 23.1 KiB
  ./node_modules/url/url.js 22.8 KiB [built] [code generated]
  ./node_modules/url/util.js 314 bytes [built] [code generated]
modules by path ./node_modules/css-loader/dist/runtime/*.js 3.84 KiB
  ./node_modules/css-loader/dist/runtime/cssWithMappingToString.js 2.27 KiB [built] [code generated]
  ./node_modules/css-loader/dist/runtime/api.js 1.57 KiB [built] [code generated]
5 modules
webpack 5.53.0 compiled successfully in 5275 ms

**Comment by mizziness** [comment]
Running `yarn dev` does indeed not output files - this is because it's running webpack dev server in HMR mode. You will only get physical files when using `yarn build`.
